### PR TITLE
Added Translated book categories and Transf Addons (pt-BR)

### PR DESCRIPTION
**Pull request by InterPlay02**
Hello!

Thank you!
And sorry, if I'm intruding too much on the project.

Bye, bye! xD

### CODE REVIEW

**Comment by Buuz135** [comment]
There is more stuff!

**Comment by InterPlay02** [comment]
Ok... Thanks for the hint! =P

**Comment by Buuz135** [comment]
Look a those changes https://github.com/Buuz135/Industrial-Foregoing/commit/9856012a56bd7b48e582e956aed2069265221a78

**Comment by InterPlay02** [comment]
What? What should I see there?
I already saw it.

**Comment by Buuz135** [comment]
My bad! I didn't saw the new stuff! I didnt get a notification for it

**Pull request merged**
