### PR TITLE
Prototyped config-based laser drill.

### PR DESCRIPTION
**Pull request by TomShkurti**
Left TODOs in areas where the JEI recipes are no longer compatible.

### CODE REVIEW

**Comment by Buuz135** [comment]
Can I get push access to your branch so I can implement the TODOs?

**Comment by TomShkurti** [comment]
Done.

**Comment by TomShkurti** [comment]
Looks good; do you think there should be some kind of wiki or readme describing the way the config files work, or do you think the default that generates is example enough?

**Comment by Buuz135** [comment]
Im going to be expanding the defaults with more, I think the only hard thing to understand is the rarity part

**Comment by TomShkurti** [comment]
We could always change the name to something like "locations" or "occurrences".

**Comment by TomShkurti** [comment]
Although, yeah, the whitelist/blacklist priority is a little opaque; I really wish JSON supported comments so all of this could be explained in the file itself.

**Comment by Buuz135** [comment]
I think the PR is good to merge, does it look good to you too?

**Comment by TomShkurti** [comment]
Looks good to me; there are some other unrelated things I might want to mess around with in this mod further down the road like adding Hookt support, but for now it's been a pleasure working with you.

**Pull request merged**
